import 'dart:io';

import 'package:asl/cubit/cubit.dart';
import 'package:asl/cubit/image_cubit.dart';
import 'package:asl/cubit/story_cubit.dart';
import 'package:asl/models/models.dart';
import 'package:asl/services/services.dart';
import 'package:asl/shared/shared.dart';
import 'package:asl/ui/widgets/widgets.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_image_compress/flutter_image_compress.dart';
import 'package:get/get.dart';
import 'package:get/route_manager.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:image_picker/image_picker.dart';
import 'package:material_design_icons_flutter/material_design_icons_flutter.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:supercharged/supercharged.dart';

part 'general_page.dart';
part 'sign_in_page.dart';
part 'sign_up_page.dart';
part 'main_page.dart';
part 'home_page.dart';
part 'detail_page.dart';
part 'post_story_page.dart';
part 'settings_page.dart';
